### ISSUE TITLE
missing image on load page

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-binder#12] opened 2018-09-30 16:26 UTC
I assume there should be a pangeo logo at the top of this page, no?

![image](https://user-images.githubusercontent.com/1197350/46259837-a1ea4b80-c4a3-11e8-8c04-ce8e51508a94.png)

**Comment by jhamman** [comment] 2018-09-30 17:41
Yes, we should fix this. I'm not sure why this isn't working. I think this page should be inhereting from the 'page.html' but something does seem to be broken.

https://github.com/pangeo-data/pangeo-custom-binderhub-templates/blob/0216d32700742c5c31204fd8be0198f25eba10d2/templates/page.html#L18-L28

I'd bet @dsludwig knows what's up here.

**Comment by rabernat** [comment] 2018-10-31 13:21
If anyone wants to fix this in the next 10 minutes that would be great. 😜

**Comment by jhamman** [comment] 2018-11-09 06:31
Hmmm, this still seems to be a problem. Will look into it more.

**Comment by andersy005** [comment] 2018-12-05 04:51
This appears to be now fixed.

**Comment by jhamman** [comment] 2018-12-05 05:18
I'm still seeing: 
![image](https://user-images.githubusercontent.com/2443309/49491690-175afb00-f80a-11e8-87d4-79057279a91a.png)

**Comment by andersy005** [comment] 2018-12-05 05:33
You are right. I was looking at the wrong page

**Comment by rabernat** [comment] 2018-12-05 14:07
This is the URL we are looking for. It exists
https://binder.pangeo.io/extra_static/pangeo_simple_logo.svg

The logo link is rending as 
```
<img id="logo" src="extra_static/pangeo_simple_logo.svg" width="390px"  />
```
with a relative, rather than absolute, URL.

The problem is with these lines:

https://github.com/pangeo-data/pangeo-binder/blob/b32b6bcf46ce25a134d5cbd67b497246c177fbaa/deploy/binder_config.yml#L13-L17

@minrk added the extra `/` to url prefix. But it didn't work. Does it need to be in quotes perhaps?

**Comment by jhamman** [comment] 2018-12-07 18:53
@rabernat - I just tried with your attempt -- no joy!. Now the image is coming from: https://staging.binder.pangeo.io/v2/gh/jhamman/dask-examples/extra_static/pangeo_simple_logo.svg

So we need to strip out the repo info: https://staging.binder.pangeo.io/extra_static/pangeo_simple_logo.svg

**Comment by bitnik** [comment] 2018-12-07 19:47
@jhamman @rabernat I think the problem is in `page.html`: https://github.com/pangeo-data/pangeo-custom-binderhub-templates/blob/master/templates/page.html#L22

Leading `/` is missing. It should be like:
```html
        <img id="logo" src={% block logo_image %}"/extra_static/pangeo_simple_logo.svg"{% endblock logo_image %} width="390px"  />
```

https://github.com/pangeo-data/pangeo-custom-binderhub-templates/pull/2 didn't fix the logo in loading page because loading page uses `loading.html` not `index.html`.

I would also delete `logo_image block` in index.html (https://github.com/pangeo-data/pangeo-custom-binderhub-templates/blob/master/templates/index.html#L10), since index.html is extending page.html and they have the same logo.

**Comment by jhamman** [comment] 2018-12-07 21:19
Thanks @bitnik. That gets us closer. Any idea why the change in https://github.com/pangeo-data/pangeo-custom-binderhub-templates/commit/17bfade90f2603f12f14da7eb13ad48953fdd917 would cause the page header css to be stripped out?

![image](https://user-images.githubusercontent.com/2443309/49673161-5794c600-fa22-11e8-8464-5463e46ee8ea.png)

**Closed** 2018-12-13 04:30 UTC
Labels: good first issue
